"""empty message

Revision ID: 4e65d9f9cb3c
Revises: 
Create Date: 2023-01-15 14:56:35.133080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e65d9f9cb3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('phoneNumber')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_user_id', sa.String(length=255), nullable=False),
    sa.Column('Subscription_id', sa.Integer(), nullable=False),
    sa.Column('Ammount', sa.Float(), nullable=False),
    sa.Column('Startime', sa.DateTime(), nullable=False),
    sa.Column('Endtime', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('payment_user_id')
    )
    op.create_table('user_video',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], )
    )
    op.create_table('workouts',
    sa.Column('workout_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_time', sa.Time(), nullable=False),
    sa.Column('username_id', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.String(length=255), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('workout_id'),
    sa.UniqueConstraint('calories'),
    sa.UniqueConstraint('strikes'),
    sa.UniqueConstraint('total_time'),
    sa.UniqueConstraint('username_id')
    )
    op.create_table('subscriptions',
    sa.Column('Subscription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Subscription_name', sa.String(length=255), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.PrimaryKeyConstraint('Subscription_id'),
    sa.UniqueConstraint('Subscription_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('workouts')
    op.drop_table('user_video')
    op.drop_table('payments')
    op.drop_table('videos')
    op.drop_table('users')
    # ### end Alembic commands ###
