"""empty message

Revision ID: 59675f1667e9
Revises: 8d21b875050e
Create Date: 2023-02-24 15:28:09.330482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59675f1667e9'
down_revision = '8d21b875050e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('streaks')
    op.drop_table('videos')
    op.drop_table('subscriptions')
    op.drop_table('users')
    op.drop_table('user_video')
    op.drop_table('workouts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('workout_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('total_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('username_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('calories', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('strikes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='workouts_user_id_fkey'),
    sa.PrimaryKeyConstraint('workout_id', name='workouts_pkey'),
    sa.UniqueConstraint('calories', name='workouts_calories_key'),
    sa.UniqueConstraint('strikes', name='workouts_strikes_key'),
    sa.UniqueConstraint('total_time', name='workouts_total_time_key'),
    sa.UniqueConstraint('username_id', name='workouts_username_id_key')
    )
    op.create_table('user_video',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_video_user_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='user_video_video_id_fkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phoneNumber', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('subscriptions',
    sa.Column('Subscription_id', sa.INTEGER(), server_default=sa.text('nextval(\'"subscriptions_Subscription_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Subscription_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name='subscriptions_payment_id_fkey'),
    sa.PrimaryKeyConstraint('Subscription_id', name='subscriptions_pkey'),
    sa.UniqueConstraint('Subscription_name', name='subscriptions_Subscription_name_key')
    )
    op.create_table('videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='videos_pkey')
    )
    op.create_table('streaks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='streaks_pkey')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Ammount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('Startime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('Endtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payments_user_id_fkey'),
    sa.PrimaryKeyConstraint('payment_id', name='payments_pkey'),
    sa.UniqueConstraint('payment_user_id', name='payments_payment_user_id_key')
    )
    # ### end Alembic commands ###
